# Generated by Django 3.2.4 on 2021-10-11 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('nacionalidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='editorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('curso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_autores', to='biblioteca.autores')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_editorial', to='biblioteca.editorial')),
                ('generos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_generos', to='biblioteca.genero')),
            ],
        ),
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPrestamo', models.DateField()),
                ('fechaDevolcion', models.DateField()),
                ('estado', models.TextField()),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_estudiante', to='biblioteca.estudiante')),
                ('idLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_libros', to='biblioteca.libros')),
            ],
        ),
    ]
