# Generated by Django 3.2.4 on 2021-10-11 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_libros_generos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='generos',
        ),
        migrations.CreateModel(
            name='generos_libros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genero')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libros')),
            ],
        ),
    ]
