# Generated by Django 3.2.4 on 2021-10-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20211011_0235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='generos_libros',
            new_name='generosLibros',
        ),
    ]
